<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net481</TargetFramework>
        <UseWPF>true</UseWPF>
        <LangVersion>default</LangVersion>
        <ApplicationIcon>Assets\2d-devworks.ico</ApplicationIcon>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <PlatformTarget>x64</PlatformTarget>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <PlatformTarget>x64</PlatformTarget>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="System.Windows.Forms" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
      <PackageReference Include="WPF-UI" Version="4.0.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GfxMan.Services\GfxMan.Services.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Resource Include="Assets\2d-devworks.ico" />
    </ItemGroup>

</Project>
